services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8181:8080"
      - "50000:50000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4096M

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - maven_cache:/home/jenkins/.m2

    user: "1000:1000"

    networks:
      - ci_network

volumes:
  jenkins_home:
    name: jenkins_data
  maven_cache:
    name: maven_repo

networks:
  ci_network:
    external: true
    name: selenium_network